local args = {
    "Special", --สามารถเปลี่ยนเป็น Special เอา gems
    0/0
}
game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("RequestBannerSummon"):InvokeServer(unpack(args))

local args = {
    "Jujutsu", --สามารถเปลี่ยนเป็น Special เอา gems
    0/0
}
game:GetService("ReplicatedStorage"):WaitForChild("Remotes"):WaitForChild("RequestBannerSummon"):InvokeServer(unpack(args))
